# Generated by Django 4.1.6 on 2023-03-21 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdjanggo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='userdjanggo_user',
        ),
    ]
